### ISSUE TITLE
Data bindings lost when loading empty pipeline

### ISSUE THREAD

**Issue by TehMillhouse** [TehMillhouse/YUV.KA#2]
When loading a .yuvka file from disk, several things can go wrong, leading to an inconsistent program state
-- Textbox below slider no longer bound to currentTick
-- PipelineDriver appears to be null, causing the program to crash when the play button is pressed

Steps to reproduce:
- start program, save empty pipeline
- load saved file
  => the ReplayStateView's slider is still working, but the textfield doesn't update.
  => When the play button is pressed, the program crashes

**Comment by Kha** [comment]
Fixed in d39938457c3ca8f9d4e72e085cec610562845383 and b253c8d37a60b7df03427930d805aed298fdb827, respectively
