### ISSUE TITLE
FileNotFoundException occurs when trying to load nonempty pipeline

### ISSUE THREAD

**Issue by TehMillhouse** [TehMillhouse/YUV.KA#3]
When trying to load a previously saved pipeline containing at least one node, the program crashes on a FileNotFoundException as it's unable to find the YuvKA.Implementation assembly necessary for loading the node type contained in the saved file

Steps to reproduce:
[[\* Open program
- Drag at least one node into PipelineView
- Save .yuvka file]]
- Load previously saved .yuvka file containing a pipeline with at least one node
  => Exception is raised

**Comment by Kha** [comment]
Fixed in fc75ef26ef90f8f0525bb1c9a75d44719e0d368d
