### ISSUE TITLE
limited replayspeed looks broken

### ISSUE THREAD

**Issue by MRVollmer** [TehMillhouse/YUV.KA#33]
when replayspeed is far lower than it takes to render, that frames are displayed in intervals of 5 frames and then sleep until it displays the next interval (is especially unintuitive with speed 1). frames should be displayed one after another in one constant speed.
reconstruction: display an input node and set framerate/speed to 1

**Comment by ghost** [comment]
Associates with the 5 frame interval which is used to adjust the speed. Guess we should enlarge this interval.
